[package]
name = "place"
version = "0.1.0"
authors = ["cpsdqs <cpsdqs@gmail.com>"]

[dependencies]
ws = "0.7"
# websocket = "0.20"
# hyper = "0.10"
# futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
base64 = "0.9"
crypto-hash = "0.3"
